name: Operator release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to be tagged and released'
        required: true
        default: '0.1.0'
      next_dev_version:
        description: 'Version for next development cycle'
        required: true
        default: '0.2.0-SNAPSHOT'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1 
      with:
        java-version: 11
    - name: Set release version
      run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.release_version }} --no-transfer-progress
    - name: Build with Maven
      run: mvn verify --file pom.xml --no-transfer-progress
    - name: Commit and tag release
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "bot: Set release version, performed by action" -a
        git tag -a ${{ github.event.inputs.release_version }} -m "Release ${{ github.event.inputs.release_version }}"
    - name: Push released main and tag
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/kubernetes/*.yml"
        tag: ${{ github.event.inputs.release_version }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ROBOTACCOUNT }}
        password: ${{ secrets.QUAY_ROBOTTOKEN }}
    - name: Build and Push Image
      run: make docker-build docker-push IMG=quay.io/redhat-developer/application-services-metering-operator:${{ github.event.inputs.release_version }}
    - name: Set next development version
      run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.next_dev_version }} --no-transfer-progress
    - name: Build with Maven
      run: mvn verify --file pom.xml --no-transfer-progress
    - name: Commit development version
      run: |
        git commit -m "bot: Set next development version, performed by action" -a
    - name: Push development main
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
